enum HandlerNum {
    READ_FILE_HANDLER = 1,
    WRITE_FILE_HANDLER = 2,
    MONITOR_FILE_HANDLER = 3,
    RESERVED_FILE_HANDLER1 = 4,
    RESERVED_FILE_HANDLER2 = 5,
    ERROR_HANDLER = 6,
    INSERTION_ACK = 7,
    NETWORK_PING = 8,
    NETWORK_ACK = 9
};