#ifndef HANDLER_ENUM
#define HANDLER_ENUM

enum HandlerNum {
    READ_FILE_REQUEST = 1,
    WRITE_FILE_REQUEST = 2,
    MONITOR_FILE_REQUEST = 3,
    RESERVED_FILE_REQUEST1 = 4,
    RESERVED_FILE_REQUEST2 = 5,
    READ_FILE_REPLY = 6,
    INSERTION_ACK = 7,
    MONITOR_FILE_ACK = 8,
    MONITOR_FILE_UPDATE = 9,
    MONITOR_FILE_EXIT = 10,
    NETWORK_PING = 15,
    NETWORK_ACK = 16,
    ERROR_REPLY = 17
};

#endif